spring:
  jpa:
    database: POSTGRESQL
  datasource:
    platform: postgres
    url: jdbc:postgresql://${IP_PG:192.168.50.210}:5432/dvdrental
    username: postgres
    password: ${PASS_PG:post123}
  database:
    driverClassname: org.postgresql.Driver
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true
server:
  contextPath: ${CONTEXT:/}
  port : ${PORT:8080}